CREATE TABLE `user` (
	`id` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '主键id',
	`user_name` VARCHAR(32) NULL DEFAULT NULL COMMENT '用户姓名',
	`nick_name` VARCHAR(32) NULL DEFAULT NULL COMMENT '用户昵称',
	`phone` VARCHAR(32) NULL DEFAULT NULL COMMENT '用户手机号',
	`email` VARCHAR(32) NULL DEFAULT NULL COMMENT '用户邮箱',
	`password` VARCHAR(64) NOT NULL COMMENT '用户密码',
	`is_deleted` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '删除字段，0未删除1已删除',
	`create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
	`update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
	PRIMARY KEY (`id`)
)
COMMENT='用户表'
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;
